apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx-pod
  labels:
    tier: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      name : nginx
      labels:
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
